# Generated by Django 3.2.4 on 2021-07-13 04:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_App', '0002_post_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(help_text='Slug is a field in autocomplete mode, but if you want you can modify its contents', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='upload',
            field=models.ImageField(blank=True, default='uploads/925667.jpg', help_text='Upload a Picture for title Image.', null=True, upload_to='imgages/'),
        ),
    ]
