# Generated by Django 3.2.4 on 2021-07-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging_App', '0007_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
